### ISSUE TITLE
akumulid aborted on bad query and didn't start after that

### ISSUE THREAD

**Issue by mmitkevich** [akumuli/Akumuli#221]
I did some query to the DB and it segfaulted. Now it doesn't start. I attach gdb traceback and SQLite db

Any way to rescue data manually?

I was just playing with querying, probably incorrectly.

```
#0  0x00007ffff568c428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff568e02a in __GI_abort () at abort.c:89
#2  0x000000000045ef23 in panic_handler (msg=0x7ffff7afe128 "Invalid rescue points state") at /home/mike/github/Akumuli/akumulid/main.cpp:517
#3  0x00007ffff79e92b6 in Akumuli::Exception::Exception (this=0x7fffffffbf70, message=0x7ffff7afe128 "Invalid rescue points state") at /home/mike/github/Akumuli/libakumuli/util.cpp:68
#4  0x00007ffff7a5b271 in Akumuli::StorageEngine::ColumnStore::open_or_restore (this=0x7b7f20, mapping=std::unordered_map with 4 elements = {...})
    at /home/mike/github/Akumuli/libakumuli/storage_engine/column_store.cpp:56
#5  0x00007ffff79ecfdc in Akumuli::Storage::Storage (this=0x788f90, path=0x785f40 "/home/mike/.akumuli/db.akumuli") at /home/mike/github/Akumuli/libakumuli/storage2.cpp:305
#6  0x00007ffff79b2fde in __gnu_cxx::new_allocator<Akumuli::Storage>::construct<Akumuli::Storage, char const*&> (this=0x7fffffffc2d7, __p=0x788f90) at /usr/include/c++/5/ext/new_allocator.h:120
#7  0x00007ffff79b26b3 in std::allocator_traits<std::allocator<Akumuli::Storage> >::construct<Akumuli::Storage, char const*&> (__a=..., __p=0x788f90) at /usr/include/c++/5/bits/alloc_traits.h:530
#8  0x00007ffff79b1f2e in std::_Sp_counted_ptr_inplace<Akumuli::Storage, std::allocator<Akumuli::Storage>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<char const*&> (this=0x788f80, __a=...)
    at /usr/include/c++/5/bits/shared_ptr_base.h:522
#9  0x00007ffff79b127b in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<Akumuli::Storage, std::allocator<Akumuli::Storage>, char const*&> (this=0x7fffffffc4a8, __a=...)
    at /usr/include/c++/5/bits/shared_ptr_base.h:617
#10 0x00007ffff79afd62 in std::__shared_ptr<Akumuli::Storage, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<Akumuli::Storage>, char const*&> (this=0x7fffffffc4a0, __tag=..., __a=...)
    at /usr/include/c++/5/bits/shared_ptr_base.h:1097
#11 0x00007ffff79aebb0 in std::shared_ptr<Akumuli::Storage>::shared_ptr<std::allocator<Akumuli::Storage>, char const*&> (this=0x7fffffffc4a0, __tag=..., __a=...) at /usr/include/c++/5/bits/shared_ptr.h:319
#12 0x00007ffff79ad99d in std::allocate_shared<Akumuli::Storage, std::allocator<Akumuli::Storage>, char const*&> (__a=...) at /usr/include/c++/5/bits/shared_ptr.h:620
#13 0x00007ffff79ac3e1 in std::make_shared<Akumuli::Storage, char const*&> () at /usr/include/c++/5/bits/shared_ptr.h:636
#14 0x00007ffff79aaeda in DatabaseImpl::DatabaseImpl (this=0x757770, path=0x785f40 "/home/mike/.akumuli/db.akumuli") at /home/mike/github/Akumuli/libakumuli/akumuli.cpp:172
#15 0x00007ffff79aafac in DatabaseImpl::create (path=0x785f40 "/home/mike/.akumuli/db.akumuli") at /home/mike/github/Akumuli/libakumuli/akumuli.cpp:181
#16 0x00007ffff79a8657 in aku_open_database (path=0x785f40 "/home/mike/.akumuli/db.akumuli", parameters=...) at /home/mike/github/Akumuli/libakumuli/akumuli.cpp:290
#17 0x00000000004966b1 in Akumuli::AkumuliConnection::AkumuliConnection (this=0x786d10, path=0x789c10 "/home/mike/.akumuli/db.akumuli") at /home/mike/github/Akumuli/akumulid/ingestion_pipeline.cpp:79
#18 0x000000000047d55e in __gnu_cxx::new_allocator<Akumuli::AkumuliConnection>::construct<Akumuli::AkumuliConnection, char const*>(Akumuli::AkumuliConnection*, char const*&&) (this=0x7fffffffc897, __p=0x786d10)
    at /usr/include/c++/5/ext/new_allocator.h:120
#19 0x000000000047c1e2 in std::allocator_traits<std::allocator<Akumuli::AkumuliConnection> >::construct<Akumuli::AkumuliConnection, char const*>(std::allocator<Akumuli::AkumuliConnection>&, Akumuli::AkumuliConnection*, char const*&&) (__a=..., __p=0x786d10) at /usr/include/c++/5/bits/alloc_traits.h:530
#20 0x000000000047a40c in std::_Sp_counted_ptr_inplace<Akumuli::AkumuliConnection, std::allocator<Akumuli::AkumuliConnection>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<char const*>(std::allocator<Akumuli::AkumuliConnection>, char const*&&) (this=0x786d00, __a=...) at /usr/include/c++/5/bits/shared_ptr_base.h:522
#21 0x000000000047759b in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<Akumuli::AkumuliConnection, std::allocator<Akumuli::AkumuliConnection>, char const*>(std::_Sp_make_shared_tag, Akumuli::AkumuliConnection*, std::allocator<Akumuli::AkumuliConnection> const&, char const*&&) (this=0x7fffffffca88, __a=...) at /usr/include/c++/5/bits/shared_ptr_base.h:617
#22 0x0000000000473670 in std::__shared_ptr<Akumuli::AkumuliConnection, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<Akumuli::AkumuliConnection>, char const*>(std::_Sp_make_shared_tag, std::allocator<Akumuli::AkumuliConnection> const&, char const*&&) (this=0x7fffffffca80, __tag=..., __a=...) at /usr/include/c++/5/bits/shared_ptr_base.h:1097
#23 0x000000000046f326 in std::shared_ptr<Akumuli::AkumuliConnection>::shared_ptr<std::allocator<Akumuli::AkumuliConnection>, char const*>(std::_Sp_make_shared_tag, std::allocator<Akumuli::AkumuliConnection> const&, char const*&&) (this=0x7fffffffca80, __tag=..., __a=...) at /usr/include/c++/5/bits/shared_ptr.h:319
#24 0x000000000046ac18 in std::allocate
[.akumuli.zip](https://github.com/akumuli/Akumuli/files/1391322/default.akumuli.zip)
_shared<Akumuli::AkumuliConnection, std::allocator<Akumuli::AkumuliConnection>, char const*>(std::allocator<Akumuli::AkumuliConnection> const&, char const*&&) (__a=...)
    at /usr/include/c++/5/bits/shared_ptr.h:620
#25 0x0000000000466f15 in std::make_shared<Akumuli::AkumuliConnection, char const*>(char const*&&) () at /usr/include/c++/5/bits/shared_ptr.h:636
#26 0x000000000045d403 in cmd_run_server () at /home/mike/github/Akumuli/akumulid/main.cpp:374
#27 0x000000000045f88b in main (argc=1, argv=0x7fffffffd868) at /home/mike/github/Akumuli/akumulid/main.cpp:605
```

**Comment by Lazin** [comment]
I can see that you're using the old version that had #161 bug that had been fixed already. 
Do you have any valuable data inside the database?

**Comment by mmitkevich** [comment]
Well not so much valuable. I'm just playing with akumuli.
I would build latest master and test
Thank you for your prompt answer.
