### ISSUE TITLE
test_storage deadlocks

### ISSUE THREAD

**Issue by smurfix** [akumuli/Akumuli#317]
I just tried to build master on an uptodate Debian 10 (buster) x64 system.
Unfortunately the storage test deadlocks.

```
strace: Process 85475 attached with 3 threads
[pid 85485] futex(0x55aa70562738, FUTEX_WAIT_PRIVATE, 6, NULL <unfinished ...>
[pid 85486] futex(0x55aa70562738, FUTEX_WAIT_PRIVATE, 6, NULL <unfinished ...>
[pid 85475] futex(0x55aa7056272c, FUTEX_WAIT_PRIVATE, 4294967295, NULL
^C
strace: Process 85475 detached
strace: Process 85485 detached
strace: Process 85486 detached

smurf@dev:~/src/akumuli$ gdb /src/akumuli/obj-x86_64-linux-gnu/unittests/test_storage 85475
GNU gdb (Debian 8.2.1-2) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /src/akumuli/obj-x86_64-linux-gnu/unittests/test_storage...done.
Attaching to program: /src/akumuli/obj-x86_64-linux-gnu/unittests/test_storage, process 85475
[New LWP 85485]
[New LWP 85486]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
futex_wait (private=<optimized out>, expected=4294967295, futex_word=0x55aa7056272c)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:61
61	../sysdeps/unix/sysv/linux/futex-internal.h: No such file or directory.
(gdb) whe
#0  futex_wait (private=<optimized out>, expected=4294967295, futex_word=0x55aa7056272c)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:61
#1  futex_wait_simple (private=<optimized out>, expected=4294967295, futex_word=0x55aa7056272c)
    at ../sysdeps/nptl/futex-internal.h:135
#2  __condvar_quiesce_and_switch_g1 (private=<optimized out>, g1index=<synthetic pointer>, wseq=<optimized out>, 
    cond=0x55aa70562718) at pthread_cond_common.c:416
#3  __pthread_cond_signal (cond=0x55aa70562718) at pthread_cond_signal.c:78
#4  0x00007f2e8d0603d9 in std::condition_variable::notify_one() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x000055aa6df31079 in Akumuli::MetadataStorage::add_rescue_point (this=0x55aa70562690, id=<optimized out>, val=...)
    at ./libakumuli/metadatastorage.cpp:391
#6  0x000055aa6df1629b in Akumuli::Storage::_update_rescue_points (rpoints=..., id=<optimized out>, 
    this=<optimized out>) at /usr/include/c++/8/bits/shared_ptr_base.h:1018
#7  Akumuli::StorageSession::write (this=0x55aa6e3e28b0, sample=...) at ./libakumuli/storage2.cpp:159
#8  0x000055aa6deea93f in fill_data (
    session=std::shared_ptr<class Akumuli::StorageSession> (use count 2, weak count 1) = {...}, begin=<optimized out>, 
    end=11000, names=std::vector of length 100, capacity 128 = {...}) at /usr/include/c++/8/bits/shared_ptr_base.h:1018
#9  0x000055aa6df05b7f in test_wal_recovery (cardinality=100, begin=1000, end=11000)
    at /usr/include/c++/8/ext/atomicity.h:96
#10 0x000055aa6df06d9c in Test_wal_recovery_1::test_method (this=<synthetic pointer>)
    at ./unittests/test_storage.cpp:1688
#11 Test_wal_recovery_1_invoker () at ./unittests/test_storage.cpp:1687
#12 0x00007f2e8d3b8f5e in boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#13 0x00007f2e8d3b8b65 in boost::execution_monitor::catch_signals(boost::function<int ()> const&) ()
   from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#14 0x00007f2e8d3b8c31 in boost::execution_monitor::execute(boost::function<int ()> const&) ()
   from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#15 0x00007f2e8d3b8cfd in boost::execution_monitor::vexecute(boost::function<void ()> const&) ()
   from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#16 0x00007f2e8d3e08a9 in boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#17 0x00007f2e8d3bb46b in ?? () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#18 0x00007f2e8d3bb72f in ?? () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#19 0x00007f2e8d3bdfd5 in boost::unit_test::framework::run(unsigned long, bool) ()
   from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#20 0x00007f2e8d3de318 in boost::unit_test::unit_test_main(bool (*)(), int, char**) ()
   from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#21 0x00007f2e8cc7009b in __libc_start_main (main=0x55aa6dee7890 <main(int, char**)>, argc=1, argv=0x7ffcb5f6acd8, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffcb5f6acc8)
    at ../csu/libc-start.c:308
#22 0x000055aa6deea2ea in _start () at ./unittests/test_storage.cpp:1758
(gdb) fr 2
#2  __condvar_quiesce_and_switch_g1 (private=<optimized out>, g1index=<synthetic pointer>, wseq=<optimized out>, 
    cond=0x55aa70562718) at pthread_cond_common.c:416
416	pthread_cond_common.c: No such file or directory.
(gdb) whe
#0  futex_wait (private=<optimized out>, expected=4294967295, futex_word=0x55aa7056272c)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:61
#1  futex_wait_simple (private=<optimized out>, expected=4294967295, futex_word=0x55aa7056272c)
    at ../sysdeps/nptl/futex-internal.h:135
#2  __condvar_quiesce_and_switch_g1 (private=<optimized out>, g1index=<synthetic pointer>, wseq=<optimized out>, 
    cond=0x55aa70562718) at pthread_cond_common.c:416
#3  __pthread_cond_signal (cond=0x55aa70562718) at pthread_cond_signal.c:78
#4  0x00007f2e8d0603d9 in std::condition_variable::notify_one() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x000055aa6df31079 in Akumuli::MetadataStorage::add_rescue_point (this=0x55aa70562690, id=<optimized out>, val=...)
    at ./libakumuli/metadatastorage.cpp:391
#6  0x000055aa6df1629b in Akumuli::Storage::_update_rescue_points (rpoints=..., id=<optimized out>, 
    this=<optimized out>) at /usr/include/c++/8/bits/shared_ptr_base.h:1018
#7  Akumuli::StorageSession::write (this=0x55aa6e3e28b0, sample=...) at ./libakumuli/storage2.cpp:159
#8  0x000055aa6deea93f in fill_data (
    session=std::shared_ptr<class Akumuli::StorageSession> (use count 2, weak count 1) = {...}, begin=<optimized out>, 
    end=11000, names=std::vector of length 100, capacity 128 = {...}) at /usr/include/c++/8/bits/shared_ptr_base.h:1018
#9  0x000055aa6df05b7f in test_wal_recovery (cardinality=100, begin=1000, end=11000)
    at /usr/include/c++/8/ext/atomicity.h:96
#10 0x000055aa6df06d9c in Test_wal_recovery_1::test_method (this=<synthetic pointer>)
    at ./unittests/test_storage.cpp:1688
#11 Test_wal_recovery_1_invoker () at ./unittests/test_storage.cpp:1687
#12 0x00007f2e8d3b8f5e in boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#13 0x00007f2e8d3b8b65 in boost::execution_monitor::catch_signals(boost::function<int ()> const&) ()
   from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#14 0x00007f2e8d3b8c31 in boost::execution_monitor::execute(boost::function<int ()> const&) ()
   from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#15 0x00007f2e8d3b8cfd in boost::execution_monitor::vexecute(boost::function<void ()> const&) ()
   from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#16 0x00007f2e8d3e08a9 in boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#17 0x00007f2e8d3bb46b in ?? () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#18 0x00007f2e8d3bb72f in ?? () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#19 0x00007f2e8d3bdfd5 in boost::unit_test::framework::run(unsigned long, bool) ()
   from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#20 0x00007f2e8d3de318 in boost::unit_test::unit_test_main(bool (*)(), int, char**) ()
   from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#21 0x00007f2e8cc7009b in __libc_start_main (main=0x55aa6dee7890 <main(int, char**)>, argc=1, argv=0x7ffcb5f6acd8, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffcb5f6acc8)
    at ../csu/libc-start.c:308
#22 0x000055aa6deea2ea in _start () at ./unittests/test_storage.cpp:1758
(gdb) fr 3
#3  __pthread_cond_signal (cond=0x55aa70562718) at pthread_cond_signal.c:78
78	pthread_cond_signal.c: No such file or directory.
(gdb) whe
#0  futex_wait (private=<optimized out>, expected=4294967295, futex_word=0x55aa7056272c)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:61
#1  futex_wait_simple (private=<optimized out>, expected=4294967295, futex_word=0x55aa7056272c)
    at ../sysdeps/nptl/futex-internal.h:135
#2  __condvar_quiesce_and_switch_g1 (private=<optimized out>, g1index=<synthetic pointer>, wseq=<optimized out>, 
    cond=0x55aa70562718) at pthread_cond_common.c:416
#3  __pthread_cond_signal (cond=0x55aa70562718) at pthread_cond_signal.c:78
#4  0x00007f2e8d0603d9 in std::condition_variable::notify_one() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x000055aa6df31079 in Akumuli::MetadataStorage::add_rescue_point (this=0x55aa70562690, id=<optimized out>, val=...)
    at ./libakumuli/metadatastorage.cpp:391
#6  0x000055aa6df1629b in Akumuli::Storage::_update_rescue_points (rpoints=..., id=<optimized out>, 
    this=<optimized out>) at /usr/include/c++/8/bits/shared_ptr_base.h:1018
#7  Akumuli::StorageSession::write (this=0x55aa6e3e28b0, sample=...) at ./libakumuli/storage2.cpp:159
#8  0x000055aa6deea93f in fill_data (
    session=std::shared_ptr<class Akumuli::StorageSession> (use count 2, weak count 1) = {...}, begin=<optimized out>, 
    end=11000, names=std::vector of length 100, capacity 128 = {...}) at /usr/include/c++/8/bits/shared_ptr_base.h:1018
#9  0x000055aa6df05b7f in test_wal_recovery (cardinality=100, begin=1000, end=11000)
    at /usr/include/c++/8/ext/atomicity.h:96
#10 0x000055aa6df06d9c in Test_wal_recovery_1::test_method (this=<synthetic pointer>)
    at ./unittests/test_storage.cpp:1688
#11 Test_wal_recovery_1_invoker () at ./unittests/test_storage.cpp:1687
#12 0x00007f2e8d3b8f5e in boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#13 0x00007f2e8d3b8b65 in boost::execution_monitor::catch_signals(boost::function<int ()> const&) ()
   from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#14 0x00007f2e8d3b8c31 in boost::execution_monitor::execute(boost::function<int ()> const&) ()
   from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#15 0x00007f2e8d3b8cfd in boost::execution_monitor::vexecute(boost::function<void ()> const&) ()
   from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#16 0x00007f2e8d3e08a9 in boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#17 0x00007f2e8d3bb46b in ?? () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#18 0x00007f2e8d3bb72f in ?? () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#19 0x00007f2e8d3bdfd5 in boost::unit_test::framework::run(unsigned long, bool) ()
   from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#20 0x00007f2e8d3de318 in boost::unit_test::unit_test_main(bool (*)(), int, char**) ()
   from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#21 0x00007f2e8cc7009b in __libc_start_main (main=0x55aa6dee7890 <main(int, char**)>, argc=1, argv=0x7ffcb5f6acd8, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffcb5f6acc8)
    at ../csu/libc-start.c:308
#22 0x000055aa6deea2ea in _start () at ./unittests/test_storage.cpp:1758
(gdb) 

```

**Comment by Lazin** [comment]
I'll take a look. Thanks for such detailed bug report!
