### ISSUE TITLE
Akumulid: SIGSEGV on insert

### ISSUE THREAD

**Issue by bbczeuz** [akumuli/Akumuli#82]
When pushing data using the following bash script, I often get SIGSEGVs:
```
#!/bin/bash
for idx in {0..1000}
do
date -u ++%Y%m%dT%H%M%S.%N | awk '{print "+testi tag1=A tag2=C tag3=I\r\n"$0"\r\n+24.3"}' | nc -C localhost 8282
done
```

Sometimes the SIGSEGV happens on the first run, sometimes after the second run. I always do a --delete, --create before testing. ~/.akumulid is original except that the storage dir was moved to some other (local) location.

gdb:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffbe866e700 (LWP 31504)]
0x0000000000489f95 in std::__atomic_base<unsigned long>::fetch_add (this=0x7ffbffffffff, __i=1, __m=std::memory_order_seq_cst)
    at /usr/include/c++/4.8.2/bits/atomic_base.h:614
614           { return __atomic_fetch_add(&_M_i, __i, __m); }
(gdb) bt
#0  0x0000000000489f95 in std::__atomic_base<unsigned long>::fetch_add (this=0x7ffbffffffff, __i=1, __m=std::memory_order_seq_cst)
    at /usr/include/c++/4.8.2/bits/atomic_base.h:614
#1  0x0000000000488485 in std::__atomic_base<unsigned long>::operator++ (this=0x7ffbffffffff) at /usr/include/c++/4.8.2/bits/atomic_base.h:388
#2  0x00000000004839c0 in Akumuli::IngestionPipeline::__lambda0::operator() (__closure=0x7dcc50) at /home/zeuz/git/Akumuli/akumulid/ingestion_pipeline.cpp:221
#3  0x00000000004852be in std::_Bind_simple<Akumuli::IngestionPipeline::start()::__lambda0()>::_M_invoke<>(std::_Index_tuple<>) (this=0x7dcc50)
    at /usr/include/c++/4.8.2/functional:1732
#4  0x0000000000485215 in std::_Bind_simple<Akumuli::IngestionPipeline::start()::__lambda0()>::operator()(void) (this=0x7dcc50)
    at /usr/include/c++/4.8.2/functional:1720
#5  0x00000000004851ae in std::thread::_Impl<std::_Bind_simple<Akumuli::IngestionPipeline::start()::__lambda0()> >::_M_run(void) (this=0x7dcc38)
    at /usr/include/c++/4.8.2/thread:115
#6  0x00007ffff5809220 in std::(anonymous namespace)::execute_native_thread_routine (__p=<optimized out>) at ../../../../../libstdc++-v3/src/c++11/thread.cc:84
#7  0x00007ffff4c66dc5 in start_thread (arg=0x7ffbe866e700) at pthread_create.c:308
#8  0x00007ffff4f7121d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```
in akumulid/ingestion_pipeline.cpp:221
```
void IngestionPipeline::start() {
[...]
                if (qref->pop(val)) {
                    idle_count = 0;
                    // New write
                    if (AKU_UNLIKELY(val->cnt == nullptr)) {  //poisoned
[...]
                    } else {
                        auto error = self->con_->write(val->sample);
HERE---->               (*val->cnt)++;
                        if (AKU_UNLIKELY(error != AKU_SUCCESS)) {
                            (*val->on_error)(error, *val->cnt);
                        }
                    }
```

It seems as the ```val``` object becomes invalid. It's not always nullptr, 0x7ffbffffffff,...
I tried initializing it to nullptr (in PipelineSpout::PipelineSpout), but this seems not to catch the issue.
(Line numbers might be a little bit off as I added more logging)

**Comment by bbczeuz** [comment]
The SIGSEGV isn't triggered if I send the data to a file first and then cat the file to Akumuli (via TCP)
-> It seems to me that there's some race condition when TCP connections come and go quickly.

**Comment by Lazin** [comment]
Fixed in master branch.
