### ISSUE TITLE
assert fail: Limiting result count

### ISSUE THREAD

**Issue by bbczeuz** [akumuli/Akumuli#87]
I was trying the 'limit' and 'offset' features: (master branch as of January 16)
```curl http://localhost:8181 --data '{ "output": { "format": "csv" }, "select": "names", "limit": 1}'```

Results in:
```
[zeuz@test-vm akumulid]$ ./akumulid
OK TCP server started, port: 8282
OK UDP server started, port: 8383
OK HTTP server started, port: 8181
akumulid: /usr/include/boost/coroutine/v1/detail/coroutine_op.hpp:266: D& boost::coroutines::detail::coroutine_op<Signature, D, void, 1>::operator()(boost::coroutines::detail::coroutine_op<Signature, D, void, 1>::arg_type) [with Signature = void(Akumuli::InternalCursor*); D = boost::coroutines::coroutine<void(Akumuli::InternalCursor*)>; boost::coroutines::detail::coroutine_op<Signature, D, void, 1>::arg_type = Akumuli::InternalCursor*]: Assertion `! static_cast< D * >( this)->impl_->is_complete()' failed.
```

Backtrace:
```
(gdb) bt
#0  0x00007ffff4e975f7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff4e98ce8 in __GI_abort () at abort.c:90
#2  0x00007ffff4e90566 in __assert_fail_base (fmt=0x7ffff4fe0228 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x7ffff7b37570 "! static_cast< D * >( this)->impl_->is_complete()", 
    file=file@entry=0x7ffff7b37510 "/usr/include/boost/coroutine/v1/detail/coroutine_op.hpp", line=line@entry=266, 
    function=function@entry=0x7ffff7b378a0 <boost::coroutines::detail::coroutine_op<void (Akumuli::InternalCursor*), boost::coroutines::coroutine<void (Akumuli::InternalCursor*), 1>, void, 1>::operator()(Akumuli::InternalCursor*)::__PRETTY_FUNCTION__> "D& boost::coroutines::detail::coroutine_op<Signature, D, void, 1>::operator()(boost::coroutines::detail::coroutine_op<Signature, D, void, 1>::arg_type) [with Signature = void(Akumuli::InternalCursor*)"...) at assert.c:92
#3  0x00007ffff4e90612 in __GI___assert_fail (assertion=0x7ffff7b37570 "! static_cast< D * >( this)->impl_->is_complete()", 
    file=0x7ffff7b37510 "/usr/include/boost/coroutine/v1/detail/coroutine_op.hpp", line=266, 
    function=0x7ffff7b378a0 <boost::coroutines::detail::coroutine_op<void (Akumuli::InternalCursor*), boost::coroutines::coroutine<void (Akumuli::InternalCursor*), 1>, void, 1>::operator()(Akumuli::InternalCursor*)::__PRETTY_FUNCTION__> "D& boost::coroutines::detail::coroutine_op<Signature, D, void, 1>::operator()(boost::coroutines::detail::coroutine_op<Signature, D, void, 1>::arg_type) [with Signature = void(Akumuli::InternalCursor*)"...) at assert.c:101
#4  0x00007ffff7aa7722 in boost::coroutines::detail::coroutine_op<void (Akumuli::InternalCursor*), boost::coroutines::coroutine<void (Akumuli::InternalCursor*), 1>, void, 1>::operator()(Akumuli::InternalCursor*) (this=0x7ffbd00013c0, a1=0x7ffbd0000ec0) at /usr/include/boost/coroutine/v1/detail/coroutine_op.hpp:266
#5  0x00007ffff7aa72c9 in Akumuli::CoroCursor::read_ex (this=0x7ffbd0000ec0, buffer=0x7ffbd0000920, buffer_size=1000)
    at /home/zeuz/git/Akumuli/libakumuli/cursor.cpp:125
#6  0x00007ffff7a75d73 in CursorImpl::read_values (this=0x7ffbd0001110, values=0x7ffbd0000920, values_size=1000) at /home/zeuz/git/Akumuli/libakumuli/akumuli.cpp:122
#7  0x00007ffff7a72a6a in aku_cursor_read (cursor=0x7ffbd0001110, dest=0x7ffbd0000920, dest_size=1000) at /home/zeuz/git/Akumuli/libakumuli/akumuli.cpp:331
#8  0x000000000047c4dd in Akumuli::AkumuliCursor::read (this=0x7ffbd0102108, dest=0x7ffbd0000920, dest_size=1000)
    at /home/zeuz/git/Akumuli/akumulid/ingestion_pipeline.cpp:27
#9  0x00000000004aa3ea in Akumuli::QueryResultsPooler::read_some (this=0x7ffbd00008c0, buf=0x7ffbd800cf4a "", buf_size=8180)
    at /home/zeuz/git/Akumuli/akumulid/query_results_pooler.cpp:380
#10 0x00000000004a6e3b in Akumuli::Http::MHD::read_callback (data=0x7ffbd00008c0, pos=0, buf=0x7ffbd800cf4a "", max=8180)
    at /home/zeuz/git/Akumuli/akumulid/httpserver.cpp:22
#11 0x00007ffff5a4b696 in try_ready_chunked_body (connection=0x7ffbd8008d30) at connection.c:442
#12 MHD_connection_handle_idle (connection=0x7ffbd8008d30) at connection.c:2379
#13 0x00007ffff5a4d2cb in MHD_handle_connection (data=0x7ffbd8008d30) at daemon.c:800
#14 0x00007ffff4c4ddc5 in start_thread (arg=0x7ffbe15f9700) at pthread_create.c:308
#15 0x00007ffff4f5821d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

**Comment by bbczeuz** [comment]
Works, thanks!
